logtrns:logtrns.cpp
	 g++ -I/usr/local/include logtrns.cpp -o logtrns -lm -lOpenCL /root/Documents/pocl/pocl-0.9/lib/poclu/.libs/libpoclu.so -Wl,-rpath -Wl,/usr/local/pocl/lib -O3 /root/Documents/PAPI/papi-5.4.1/src/libpapi.a
